WebApplication2/WebApplication2/Models/Event.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication2.Models
{
    public class Event

    {
        public string RoomName { get; set; }
        //public string RoomID { get; set; }
        //public string EventID { get; set; }
        public string  StartTime { get; set; }
        public string EndTime { get; set; }

        public string Subject { get; set; }
        public string Requestor { get; set; }

    }
}

WebApplication2/WebApplication2/Models/Room.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication2.Models
{
    public class Room
    {
        public string Name { get; set; }
        public string Capacity { get; set; }

    }
}

WebApplication2/WebApplication2/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using WebApplication2.Models;
using System.IO;
using System.Linq;

namespace WebApplication2.Controllers
{
    public class RoomController : Controller
    {

        // GET: Room
        public ActionResult Index()
        {
            List<Room> rooms = new List<Room>();

            var csvColumn = new List<string>();

            using (var rd = new StreamReader(@"C:\Temp\RoomList.csv"))
            {
                while (!rd.EndOfStream)
                {
                    var splits = rd.ReadLine().Split(';');
                    csvColumn.Add(splits[0]);
                }
            }
            int i = 1;
            foreach (var element in csvColumn)
            {

                string str = element;
                string[] tokens = str.Split('(');
                string CrName = tokens[0];// + " " + tokens[1];
                string[] tokens2 = CrName.Split(',');
                CrName = tokens2[1];

                string CrCapacity = tokens[1];
                CrCapacity = CrCapacity.Remove(CrCapacity.Length - 1);
                rooms.Add(new Room() { Name = CrName, Capacity = CrCapacity });// capacity="12"});
                i++;
            }

            return View("Index", rooms);
        }

       
        
      
        public ActionResult ShowEvents(string roomName) 
        {
                List<Event> events = new List<Event>();

            //----------EventsDetails----------------
                roomName = roomName.Trim();
            
                string path = @"C:\Temp\Rooms.csv";
              
                string EndDate;
                string Requestor;
                string Subject;
                string StartDate;

                List<string> SearchedLines = new List<string>();
                int counter = 0;
                string line;
                // Read the file and display it line by line.
                System.IO.StreamReader file = new System.IO.StreamReader(path);
                while ((line = file.ReadLine()) != null)
                {
                    if (line.Contains(roomName))
                    {
                        string evcount = System.IO.File.ReadLines(path).Skip(counter + 1).Take(2).First();

                        if (evcount == "0")
                        {
                            events.Add(new Event()
                            {
                                RoomName = roomName,
                                StartTime = "0",
                                EndTime = "0",
                                Requestor = "0",
                                Subject = "0"
                            });
                        }
                        else
                        {
                            int c = Int32.Parse(evcount);
                            for (int i = 0; i < c; i++)
                            {
                               // Console.WriteLine("there are {0} events", counter.ToString());
                               // counter = counter + i + c;
                                StartDate = System.IO.File.ReadLines(path).Skip(counter+2).Take(2).First();
                                //  Console.WriteLine(StartDate);
                                EndDate = System.IO.File.ReadLines(path).Skip(counter + 3).Take(2).First();
                                // Console.WriteLine(EndDate);
                                Requestor = System.IO.File.ReadLines(path).Skip(counter + 4).Take(2).First();
                                // Console.WriteLine(Requestor);
                                Subject = System.IO.File.ReadLines(path).Skip(counter + 5).Take(2).First();
                                // Console.WriteLine(Subject);
                                events.Add(new Event()
                                {
                                    RoomName = roomName,
                                    StartTime = StartDate,
                                    EndTime = EndDate,
                                    Requestor = Requestor,
                                    Subject = Subject
                                });
                            counter = counter + 4;
                        }
                     }
                    }
                    counter++;
                }
                //Console.WriteLine(events.Count.ToString());
                //Console.WriteLine("Done");
                //Console.ReadKey();
                return View("ShowEvents", events);
        }
    }
}

WebApplication2/WebApplication2/Views/DynamicEventsContent.cshtml
@model WebApplication2.Models.Event

WebApplication2/WebApplication2/Views/Room/Index.cshtml
@model IEnumerable<WebApplication2.Models.Room>



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />


    <title>Index</title>
</head>
<body>

    <p>
        <h1>Conference rooms list : </h1>
    </p>
    <table class="table">
        <tr>

            @*<th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Capacity)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                @*<td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Capacity)
                </td>
                <td>
                    
                    @Html.ActionLink("GetEvents", "ShowEvents", "Room", new { roomName = item.Name}, null)

                    @*@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ }*@
                </td>
            </tr>
        }

    </table>
</body>
</html>

WebApplication2/WebApplication2/Views/Room/ShowEvents.cshtml
@model IEnumerable<WebApplication2.Models.Event>
<script src="~/scripts/Clock.js"></script>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script type="text/javascript">

        function FullScreenMode() {
            var wscript = new ActiveXObject("WScript.Shell");
            if (wscript != null) {
                wscript.SendKeys("{F11}");
            }
        }
    </script>

    <script>
        function DiplayClock() {
            var currentTime = updateClock();
            document.getElementById("clock").firstChild.nodeValue = currentTime;
        }
    </script>
    
   

</head>
<body onload="DiplayClock(); setInterval('DiplayClock()', 1000);">
  
       <script type="text/javascript">FullScreenMode();</script>

        <div class="date-time">
            <span id="clock">&nbsp;</span>
        </div>

        @{
            int i = 0;

            foreach (var model in Model)
            {

                i++;
            } }
        <p>
            <h1>Events for CR : @Model.First().RoomName</h1>
        </p>
        @{
            DateTime CurTime = DateTime.Now;

            if (Model.First().StartTime != "0")
            {
                foreach (var model in Model)
                {
                    if ((CurTime >= (DateTime.Parse(model.StartTime))) && (CurTime <= (DateTime.Parse(model.EndTime))))
                    {
                        <h3> Conference room is occupied now! </h3>
                        string EndTime = model.EndTime;
                        string StartTime = model.StartTime;
                        string Requestor = model.Requestor;
                        string Subject = model.Subject;

                        <h4>Start time : @StartTime</h4>
                        <h4>End time : @EndTime</h4>
                        <h4>Requestor : @Requestor</h4>
                        <h4>Subject : @Html.Raw(Subject)</h4>
                        string EndMin = (DateTime.Parse(model.EndTime) - CurTime).ToString();

                        <h2>Ends in : @EndMin</h2>
                    }

                    else if ((CurTime < (DateTime.Parse(model.StartTime))) && (CurTime < (DateTime.Parse(model.EndTime))))
                    {

                        <h3> Conference room is free now! </h3>
                        string EndTime = model.EndTime;
                        string StartTime = model.StartTime;
                        string Requestor = model.Requestor;
                        string Subject = model.Subject;

                        TimeSpan ts = (CurTime - DateTime.Parse(model.StartTime));
                        ts = ts.Negate();
                        string EndMin = ts.ToString();
                        <p>
                            <h2>Next event starts in : @EndMin</h2>

                            <h4>Start time : @StartTime</h4>
                            <h4>End time : @EndTime</h4>
                            <h4>Requestor : @Requestor</h4>
                            <h4>Subject : @Html.Raw(Subject) </h4>
                        </p>
                    }
                }
            }
            else
            {
                @:<h3> Conference room is free now </h3>
        }
        }

        @if (Model.First().StartTime == "0")
        {
            @:<h2>There are no events for today yet</h2>
                            }
        else
        {
            @:<h3> Conference room is free now </h3>
            <h2>Events for today : @i.ToString()</h2>
                                <table class="table">
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.StartTime)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.EndTime)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Subject)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Requestor)
                                        </th>
                                        <th></th>
                                    </tr>

                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.StartTime)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.EndTime)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Subject)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Requestor)
                                            </td>
                                        </tr>
                                    }
                                </table>
        }
    </body>

</html>

WebApplication2/WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")"></script>
</head>
<body>
    @*<ul id="menu">
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("Movies", "Index", "Movies")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
    </ul>*@
    <section id="main">
        @RenderBody()
        
    </section>
</body>
</html>